### YamlMime:UniversalReference
items:
  - uid: merge-styles.ICSPSettings
    summary: CSP settings for the stylesheet
    name: ICSPSettings
    fullName: ICSPSettings
    langs:
      - typeScript
    type: interface
    package: merge-styles
    children:
      - merge-styles.ICSPSettings.nonce
  - uid: merge-styles.ICSPSettings.nonce
    summary: Nonce to inject into script tag
    name: nonce
    fullName: nonce
    langs:
      - typeScript
    type: property
    syntax:
      content: 'nonce?: string;'
      return:
        type:
          - string
