### YamlMime:UniversalReference
items:
  - uid: merge-styles.IStyleSheetConfig
    summary: Stylesheet config.
    name: IStyleSheetConfig
    fullName: IStyleSheetConfig
    langs:
      - typeScript
    type: interface
    package: merge-styles
    children:
      - merge-styles.IStyleSheetConfig.cspSettings
      - merge-styles.IStyleSheetConfig.defaultPrefix
      - merge-styles.IStyleSheetConfig.injectionMode
      - merge-styles.IStyleSheetConfig.namespace
      - merge-styles.IStyleSheetConfig.onInsertRule
  - uid: merge-styles.IStyleSheetConfig.cspSettings
    summary: CSP settings
    name: cspSettings
    fullName: cspSettings
    langs:
      - typeScript
    type: property
    syntax:
      content: 'cspSettings?: ICSPSettings;'
      return:
        type:
          - merge-styles.ICSPSettings
  - uid: merge-styles.IStyleSheetConfig.defaultPrefix
    summary: Default 'displayName' to use for a className.
    name: defaultPrefix
    fullName: defaultPrefix
    langs:
      - typeScript
    type: property
    syntax:
      content: 'defaultPrefix?: string;'
      return:
        type:
          - string
  - uid: merge-styles.IStyleSheetConfig.injectionMode
    summary: Injection mode for how rules are inserted.
    name: injectionMode
    fullName: injectionMode
    langs:
      - typeScript
    type: property
    syntax:
      content: 'injectionMode?: InjectionMode;'
      return:
        type:
          - InjectionMode
  - uid: merge-styles.IStyleSheetConfig.namespace
    summary: Default 'namespace' to attach before the className.
    name: namespace
    fullName: namespace
    langs:
      - typeScript
    type: property
    syntax:
      content: 'namespace?: string;'
      return:
        type:
          - string
  - uid: merge-styles.IStyleSheetConfig.onInsertRule
    summary: Callback executed when a rule is inserted.
    name: onInsertRule
    fullName: onInsertRule
    langs:
      - typeScript
    type: property
    syntax:
      content: 'onInsertRule?: (rule: string) => void;'
      return:
        type:
          - '(rule: string) => void'
